---
- name: Update RHEL
  yum:
    name: "*"
    state: latest
    update_cache: true

- name: Output Ansible OS Family
  debug:
    msg: "{{ ansible_os_family }}"

# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  when: not nginx_use_scl

- name: Include OS-specific variables (RedHat SCL).
  include_vars: "{{ ansible_os_family }}-SCL.yml"
  when: nginx_use_scl

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- include_tasks: setup-OpenBSD.yml
  when: ansible_os_family == 'OpenBSD'

- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

# - name: Change owner of nginx pid
#   file:
#     path: "{{ nginx_pidfile }}"
#     owner: "{{ nginx_user }}"
#     group: "{{ nginx_user }}"

# Vhost configuration.
- import_tasks: vhosts.yml

# - import_tasks: scl_systemd_setup.yml
#   when: nginx_use_scl

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - restart nginx

# - name: Ensure nginx service is running as configured.
#   service:
#     name: "{{ nginx_service_name }}"
#     state: "{{ nginx_service_state }}"
#     enabled: "{{ nginx_service_enabled }}"
